import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./styles/layout.module.css";
import Header from "./components/header";
import Nav from "./components/nav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` ${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header />
        <span className={styles.page}>{children}</span>
        <Nav />
      </body>
    </html>
  );
}
